version: "3.7"
services:
  frontend:
    image: docker.io/adinaclaudiatoma/docker-ws-frontend:1.0
    build:
      context: todo-frontend
      # backend port needs to be passed as build arg because it's used in the build/compile stage, not at runtime
      args:
        BACKEND_HOST: localhost
        BACKEND_PORT: 3333
    ports:
      - 8080:80
    restart: always
    networks:
      - react-express
    depends_on:
      - backend

  backend:
    image: docker.io/adinaclaudiatoma/docker-ws-backend:1.0
    build:
      context: todo-backend
    environment:
      PORT: 3333
      DB_HOST: pg
      DB_PORT: 5432
      DB_USER: postgres
      DB_PASSWORD: ${PASSWORD}
    ports:
      - 3333:3333
    restart: always
    depends_on:
      pg:
        condition: service_started
    networks:
      - express-postgres
      - react-express

  pg:
    image: postgres:13
    restart: always
    environment:
      POSTGRES_PASSWORD: ${PASSWORD}
    volumes:
      - ./postgres/data:/var/lib/postgresql/data
      - ./postgres/docker-entrypoint-initdb.d:/docker-entrypoint-initdb.d
    networks:
      - express-postgres
networks:
  react-express:
  express-postgres: